### ISSUE TITLE
Notebook

### ISSUE THREAD

**Issue by HackerMan1993** [HackerMan1993/Sports_Revenue_Fans_Etc#2]
Hi @AaronGullickson . It's crude but I've submitted my lab notebook. I'd like to meet with you next week to figure out what to do now, if that's possible.

**Comment by AaronGullickson** [comment]
@HackerMan1993 Ok, but you haven't created executable R code chunks. You need to put `{r name}` after the opening fencing to get it to process.

**Comment by HackerMan1993** [comment]
@AaronGullickson Would you like me to redo this part?

**Comment by AaronGullickson** [comment]
@HackerMan1993 No just for your info.

**Comment by HackerMan1993** [comment]
@AaronGullickson I ended up redoing it anyways in order to actually have code chunks and to help with the paper; again, my merging ability is god-awful and I can't get things to work to get them to you.
![Notebook](https://user-images.githubusercontent.com/47223689/59557830-c2f2be00-8f98-11e9-8651-c1d5effaebb7.png)
